import "./globals.css";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";

import { ConfettiProvider } from "@/components/providers/confetti-provider";
import { ToasterProvider } from "@/components/providers/toaster-provider";
import Provider from "@/components/providers/next-auth-provider";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ChakraProvider>
            <ConfettiProvider />
            <ToasterProvider />
            {children}
          </ChakraProvider>
        </Provider>
      </body>
    </html>
  );
}
